name: build and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Login to Digital Ocean Registry
      uses: docker/login-action@v1
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

    - name: Build latest
      run: docker build -t registry.digitalocean.com/containers/kubbis:$(echo $GITHUB_SHA | head -c7) .

    - name: DigitalOcean Kubernetes
      uses: matootie/dokube@v1.4.0
      with:
        personalAccessToken: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        clusterName: k8s-bergen
        expirationTime: 600 # optional, default is 600
        # The Kubernetes namespace to operate under.
        namespace: apps
        # The kubectl version to use.
        version: 1.21.9 # optional, default is 1.21.9

    - name: Push image to DO Container Registry 
      run: docker push registry.digitalocean.com/containers/kubbis:$(echo $GITHUB_SHA | head -c7) .

  
      

